# ReplicationController with one container template and 3 replicas.

apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: mypod-pod
      type: nginx
    spec:
      container:
        - name: nginx-container
          image: nginx
  replicas: 3
