apiVersion: apps/v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  # type of services.
  # type can be NodePort, or ClustIp, or LoadBalancer
  ports:
    - targetport: 80
      port: 80
      nodeport: 30008
  selector:
    # PODs label's section
    app: myapp
    type: frontend
